mozilla/bugzy

- src/content/components/BugList/columnTransforms.js
I could be wrong but I think this got missed in 578d63ae669b3e30336a6c4b12f3041dd82cd4c2?
> Bug fix: push correct has-pr tag

- src/config/tags.js
- src/content/components/BugList/columnTransforms.js
Wasn't sure about the style of the chore tags - these are purple on white
> Fix #28: Add 'chore' tags

- src/content/components/Router/Router.js
- src/content/components/Router/Router.scss
- src/content/components/Uplift/Uplift.js
- src/content/components/Uplift/Uplift.scss
- src/content/img/icons/up-arrow.svg
(The [icon](https://www.flaticon.com/free-icon/up-arrow_137608) comes from an existing icon source)
> Fix #47: add uplift view

- src/common/iterationUtils.js
Blocker: Couldn't see what bugs we have planned 😅
> Fix Bug 58 - Add Exception for 63 long cycle

- src/content/components/FeatureView/FeatureView.js
Adds some separation of bugs by meta in the engineering view, only for open P1 bugs for now.
Try this by taking a look at http://localhost:1989/feature/1536844 for example, notice how sub metas now have their own sections
> Sort bugs in FeatureView by subMeta

- src/config/people.js
- src/content/components/BugList/columnTransforms.js
- src/content/components/FeatureView/FeatureView.js
- src/content/components/Router/Router.js
- src/schema/customfields.json
- src/schema/query_options.js
> Fixes #115 - Remove uiwanted view and add label by designers need info

- src/content/components/CompletionBar/CompletionBar.js
- src/content/components/CompletionBar/CompletionBar.scss
- src/content/components/FeatureView/FeatureView.js
- src/content/components/IterationView/IterationView.js
Duplicated the CompletionBar & its usage from the Iteration view. Seems to be able to work off existing props.
> Added the CompletionBar component to the Feature view

- package.json
- src/content/components/PriorityGuide/PriorityGuide.js
- src/content/components/PriorityGuide/PriorityGuide.scss
- src/content/img/icons/arrow-d-dark.svg
- src/content/img/icons/arrow-l-dark.svg
- src/content/img/icons/arrow-r-dark.svg
- src/content/img/icons/overflow.svg
It toggles! Still have to work on replacing the button with a nice icon.
> Bug 57 - Make priority sidebar collapsable

- src/content/components/MyBugs/MyBugs.js
I run into this issue a lot because my browser is set to clear cache/cookies on quit.
> (nobug) - Update MyBugs page on form submit

- nodemon.json
This is annoying for local dev
> (nobug) Don't restart nodemon on react/scss changes

- src/config/project_settings.js
- src/content/components/FeatureView/FeatureView.js
- src/content/components/ui/FileNewBugButton/FileNewBugButton.js
- src/server.ts
Modified the FileNewBugButton to check the bug meta for the correct component; minor query refactor
> bug 145 - Update file new bug buttons

- package-lock.json
- package.json
- src/content/components/ActiveRSMessages/ActiveRSMessages.scss
- src/content/components/ActiveRSMessages/ActiveRSMessages.tsx
- src/content/components/ActiveRSMessages/TargetingParser.ts
- src/content/components/Router/Router.js
- src/server.ts
- src/server/queryUtils.ts
- tsconfig.json
There's one more thing I want to add: a link from the message to the redash dashboard.
> Preview Remote Settings messages in Bugzy

- src/bin/buildRange.ts
Added the dates for 86 & 87+ as a quick fix while I look at updating the API. Pretty sure I counted correctly :)
> add date ranges for ff86 & 87+

- .nvmrc
> Add a .nvmrc file

- src/content/components/MyBugs/MyBugs.scss
Fixes [Issue #209 ](https://github.com/mozilla/bugzy/issues/209)
> fix: Add 'pointer' cursor to gear icon on My Bugs view

- src/content/components/Loader/MiniLoader.css
Clean up some unnecessary CSS rules leftover from 415f6d7
> style: 🎨 Clean up miniloader CSS

- src/bin/buildRange.ts
> Update iterations for the one-off 110.3

- src/content/components/Loader/Loader.js
> feat: add tooltip to MiniLoader

- package-lock.json
- package.json
- src/common/iterationUtils.ts
- src/content/components/IterationPicker/IterationPicker.tsx
- src/content/components/IterationView/IterationView.tsx
- src/content/components/OtherView/OtherView.tsx
- src/content/components/Router/Router.js
> feat: add an iteration picker

- src/config/pref_defaults.js
- src/content/lib/prefs.js
> fix: use default values in prefs/store system

- src/content/components/IterationPicker/IterationPicker.tsx
- src/content/components/Router/Router.scss
> feat: add year to iteration picker

- .eslintrc.js
- src/content/components/AllocationView/AllocationView.js
- src/content/components/BugList/columnTransforms.js
- src/content/components/PriorityGuide/PriorityGuide.js
- src/content/components/PriorityGuide/PriorityGuide.scss
- src/schema/query_options.js
> Change Points to Size, add it to priority guide

- src/config/people.js
- src/content/components/IterationView/IterationView.tsx
- src/content/components/PriorityGuide/PriorityGuide.scss
- src/server/queryUtils.ts
> [FR] Add Finished Work per person display to IterationView

- src/common/IterationLookup.ts
- src/content/components/IterationView/IterationView.module.scss
- src/content/components/IterationView/IterationView.tsx
- src/content/components/Router/Router.js
> Add arrow buttons on either side of the title on IterationView to go to previous/next iteration

- src/content/components/BugList/columnTransforms.js
- src/content/components/BugListView/BugListView.js
- src/content/components/FeatureView/FeatureView.js
- src/content/components/Router/Router.js
- src/content/styles/gStyles.module.scss
> Allow viewing meta bugs as bugzy features even if they don't block the bugzy epic

- src/content/components/MyBugs/MyBugs.js
> Issue 293 - Add priority and sizing columns to My Bugs lists
